---
- name: Download k3s binary
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/v1.22.10+k3s1/k3s
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/v1.22.10+k3s1/sha256sum-amd64.txt
    dest: /usr/local/bin/k3s
    mode: 0755