---
- name: Create manifest directory
  file:
   path: /var/lib/rancher/k3s/server/manifests
   state: directory
   mode: 0644

- name: Copy basic manifest
  block:
    - name: copy kube-vip rbac
      template:
        src: "kube-vip-rbac.yaml.j2"
        dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml"
        mode: 0644

    - name: copy kube-vip daemonset
      template:
        src: "kube-vip-ds.yaml.j2" 
        dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-ds.yaml"

- name: Copy k3s service file
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    mode: 0644
#
# Silly things but work
#
- name: Enable and check K3s service (init master)
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: init_master == True
  ignore_errors: true

- name: pause, waiting master
  pause:
    seconds: 60

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: init_master == False
  ignore_errors: true