---
# Default location /etc/rancher/k3s/k3s.yaml
- name: Replace https://localhost:6443 by https://virtual_ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ virtual_ip }}:6443
  changed_when: true
