---
- name: Copy k3s service file
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s-worker.service"
    mode: 0644

- name: Enable and check k3s service
  systemd:
    name: k3s-worker
    daemon_reload: yes
    state: restarted
    enabled: yes
