---
- name: Enable kernel modules runtime
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernel_tuning }}"

- name: Enable kernel modules on boot
  ansible.builtin.copy:
    mode: "0644"
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  loop: "{{ kernel_tuning }}"

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
